# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           myhome2.github.io
#relative_permalinks: true

# Setup
title:               MyHome
tagline:             'MyHome'
description:         'MyHome Site'
url:                 http://myhome2.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Alexey Shikharbeev
  url:               
  email:             myhome@samopal.pro

# Custom vars
version:             1.0.0
