title: MyHome
email: myhome@samopal.pro
description: Страница по MyHome контроллеру
baseurl: ''
url: ''
twitter_username: null
github_username: myhome2
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
